org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.debug=false

minecraft_version=1.21.1
neoforge_version=21.1.172
mod_id=customtab
mod_name=CustomTab
mod_version=1.0.0
mod_group_id=com.kingmihailp.customtab
mod_authors=kingmihailp
mod_description=Fully customizable tab list with image support for server administrators.
